version: '2'
services:
    hcrespirar-app:
        image: hcrespirar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hcrespirar-mysql:3306/hcrespirar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hcrespirar-mysql:
        extends:
            file: mysql.yml
            service: hcrespirar-mysql
